global:
  namespace: find-fuel
  environment: dev

dbEnvConfigMap:
  name: db-env-config-map
  data:
    DB_DRIVER: postgres
    DB_HOST: postgres-cluster-rw.find-fuel-cnpg-db.svc.cluster.local
    DB_PORT: 5432
    DB_USER: postgres
    DB_PASSWORD: postgres
    DB_NAME: postgres
    DB_SSLMODE: require

appEnvConfigMap:
  name: app-env-config-map
  data:
    HOST: ""
    PORT: 9090
    STATICFILES_DIR: /var/www/static
    HEALTHCHECK_ROUTE: /health
    LOG_HEALTHCHECK_REQUESTS: false
    AUTH_ENABLED: false

app:
  name: find-fuel-app
  deployment:
    replicaCount: 1
    image: find-fuel-app
  service:
    port: 80
    nodePort: 30090
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  livenessProbe:
    httpGet:
      path: /health
      port: 
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /health
      port: 
    initialDelaySeconds: 5
    periodSeconds: 5

migrations:
  name: find-fuel-migrations
  job:
    image: find-fuel-migrations
    backoffLimit: 3

updateData:
  name: find-fuel-update-data
  cronJob: 
    schedule: "0 0,12 * * *"
    image: find-fuel-update-data