apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ .Values.updateData.name }}-cronjob"
  namespace: {{ .Values.global.namespace }}
spec:
  schedule: "{{ .Values.updateData.cronJob.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: "{{ .Values.updateData.name }}-cronjob"
        spec:
          restartPolicy: OnFailure
          containers:
          - name: {{ .Values.updateData.name }}
            image: {{ .Values.updateData.cronJob.image }}
            imagePullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: {{ .Values.dbEnvConfigMap.name }}
          
